engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false

  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - ruby
      	#mass_threshold: 30
      - javascript
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- node_modules/
- server/tests/
- template/bootstrap/
- template/bootstrap4/