
language: node_js
node_js:
  - "6.10.0"
services:
  - postgresql
 
before_script:
  - npm install -g sequelize-cli
  - sudo -u postgres createuser mcdavid
  - createdb postit-dev

script:
  - npm run test