
language: node_js
node_js:
  - "node"
  - "6.10.0"
services:
  - postgresql
  
group: deprecated-2017Q3
 
before_script:
  - npm install -g sequelize-cli
  - sudo -u postgres createuser mcdavid
  - createdb postit-dev

script:
  - npm run test
